### ISSUE TITLE
Init settings getting overrided

### ISSUE THREAD

**Issue by marcellino-ornelas** [njhoffman/prettyjson-256#2]
```
const a = {
  name: {
    age: {
      name: 'name',
      three: 'three',
      next: {
        another: {
          hey: 'hey',
          bye: 'bye'
        }
      }
    }
  }
};

pjson.init({
  depth: 3
});

console.log(pjson.render(a));
console.log('=====================================');
console.log(pjson.render(a, 2, { depth: 2 }));
console.log('=====================================');
console.log(pjson.render(a));
```
<img width="714" alt="Screen Shot 2019-07-26 at 6 33 02 PM" src="https://user-images.githubusercontent.com/35247622/61988270-d3547a80-afd3-11e9-9a3b-61b27d8cc4f8.png">

expected the last one to display as the first one did

**Comment by njhoffman** [comment]
Thank you for the report, sorry about the delay but I fixed this issue plus made a lot of other updates and fixes for v1.6.0.  I will look at the next issue soon, submit anything else you find thanks again.
